/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ksi;

/**
 *
 * @author Biekaeksa
 */
public class FormPolyalphabeticalTwoKey extends javax.swing.JFrame {
    private char[] textGenerateNow1 = new char[26];
    private char[] textGenerateNow2 = new char[26];
    char[] textArray1;
    char[] textArray2;
    int kliken = 0;
    int klikdek = 0;

    /**
     * Creates new form FormPlyalphabeticalTwoKey
     */
    public FormPolyalphabeticalTwoKey() {
        initComponents();
    }

    private void generateKeyOne(String key) {
        String abcd = "abcdefghijklmnopqrstuvwxyz";
        textArray1 = abcd.toCharArray();
        char[] keyArr = key.toLowerCase().toCharArray();

        for (int i = 0; i < 26; i++) {
            if (i < keyArr.length) {
                textGenerateNow1[i] = keyArr[i];
            } else {
                for (int j = 0; j < 26; j++) {
                    boolean ketemu = false;
                    for (int k = 0; k < i + 1; k++) {
                        if (textGenerateNow1[k] == textArray1[j]) {
                            ketemu = true;
                        }
                    }
                    if (!ketemu) {
                        textGenerateNow1[i] = textArray1[j];
                        break;
                    }
                }
            }

        }

    }

    private void generateKeyTwo(String key) {
        String abcd = "abcdefghijklmnopqrstuvwxyz";

        textArray2 = abcd.toCharArray();
        char[] keyArr = key.toLowerCase().toCharArray();

        for (int i = 0; i < 26; i++) {
            if (i < keyArr.length) {
                textGenerateNow2[i] = keyArr[i];
            } else {
                for (int j = 0; j < 26; j++) {
                    boolean ketemu = false;
                    for (int k = 0; k < i + 1; k++) {
                        if (textGenerateNow2[k] == textArray2[j]) {
                            ketemu = true;
                        }
                    }
                    if (!ketemu) {
                        textGenerateNow2[i] = textArray2[j];
                        break;
                    }
                }
            }

        }
        for (int l = 0; l < textGenerateNow2.length; l++) {
            abcd += textGenerateNow2[l];
        }
        System.out.println(abcd);

    }

    private String enkripsi(String plainText, String key1, String key2) {
        if (kliken == 0 && klikdek != 1) {
            generateKeyOne(key1);
            generateKeyTwo(key2);
            kliken = 1;
        }

        char[] plainTextArr = plainText.toLowerCase().toCharArray();
        String chipperText = "";

        for (int i = 0; i < plainTextArr.length; i++) {
            int position = 0;
            int finalPosition = 0;
            for (int j = 0; j < 26; j++) {
                if (plainTextArr[i] == textArray1[j]) {
                    position = j;
                }
            }
            for (int k = 0; k < 26; k++) {
                if (textGenerateNow1[position] == textArray1[k]) {
                    finalPosition = k;
                }
            }
            if (plainTextArr[i] == ' ') {
                chipperText += ' ';
            } else {
                chipperText += textGenerateNow2[finalPosition];
            }

        }

        return chipperText;
    }

    private String dekripsi(String chipperText, String key1, String key2) {
        if (kliken != 1 && klikdek == 0) {
            generateKeyOne(key1);
            generateKeyTwo(key2);
            klikdek = 1;
        }
        char[] chipperTextArr = chipperText.toLowerCase().toCharArray();
        String plainText = "";

        for (int i = 0; i < chipperTextArr.length; i++) {
            int position = 0;
            int finalPosition = 0;
            for (int j = 0; j < 26; j++) {
                if (chipperTextArr[i] == textGenerateNow2[j]) {
                    position = j;
                }
            }

            for (int k = 0; k < 26; k++) {
                if (textArray2[position] == textGenerateNow1[k]) {
                    finalPosition = k;
                }
            }
            if (chipperTextArr[i] == ' ') {
                plainText += ' ';
            } else {
                plainText += textArray1[finalPosition];
            }

        }

        return plainText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldChipperTeksDek = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldKunciDek1 = new javax.swing.JTextField();
        fieldPlainTeksEn = new javax.swing.JTextField();
        buttonProsesDek = new javax.swing.JButton();
        fieldKunciEn1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        buttonProsesEn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fieldChipperTeksEn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldPlainTeksDek = new javax.swing.JTextField();
        fieldKunciDek2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldKunciEn2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        buttonReset1 = new javax.swing.JButton();
        buttonReset2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Chippe Teks");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("ENKRIPSI TEKNIK POLYALPHABETICAL");

        jLabel7.setText("Kunci 1");

        jLabel2.setText("Plain Teks");

        fieldChipperTeksDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldChipperTeksDekActionPerformed(evt);
            }
        });

        jLabel3.setText("Kunci 1");

        fieldKunciDek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciDek1ActionPerformed(evt);
            }
        });

        fieldPlainTeksEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlainTeksEnActionPerformed(evt);
            }
        });

        buttonProsesDek.setText("Proses");
        buttonProsesDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesDekActionPerformed(evt);
            }
        });

        fieldKunciEn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciEn1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Plain Teks");

        buttonProsesEn.setText("Proses");
        buttonProsesEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesEnActionPerformed(evt);
            }
        });

        jLabel4.setText("Chipper Teks");

        fieldChipperTeksEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldChipperTeksEnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("DEKRIPSI TEKNIK POLYALPHABETICAL");

        fieldPlainTeksDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlainTeksDekActionPerformed(evt);
            }
        });

        fieldKunciDek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciDek2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Kunci 2");

        fieldKunciEn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciEn2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Kunci 2");

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        buttonReset1.setText("Reset Kunci");
        buttonReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReset1ActionPerformed(evt);
            }
        });

        buttonReset2.setText("Reset Kunci");
        buttonReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldChipperTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldChipperTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldKunciDek1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldKunciDek2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonProsesDek))
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonReset2))
                                    .addComponent(fieldPlainTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPlainTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonProsesEn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldKunciEn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldKunciEn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonReset1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonKembali)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPlainTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(fieldKunciEn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fieldKunciEn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buttonReset1)))
                .addGap(21, 21, 21)
                .addComponent(buttonProsesEn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldChipperTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fieldChipperTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(fieldKunciDek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldKunciDek2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buttonReset2)))
                .addGap(18, 18, 18)
                .addComponent(buttonProsesDek)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPlainTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buttonKembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldChipperTeksDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldChipperTeksDekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldChipperTeksDekActionPerformed

    private void fieldKunciDek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciDek1ActionPerformed

    }//GEN-LAST:event_fieldKunciDek1ActionPerformed

    private void fieldPlainTeksEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlainTeksEnActionPerformed

    }//GEN-LAST:event_fieldPlainTeksEnActionPerformed

    private void buttonProsesDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesDekActionPerformed

        fieldPlainTeksDek.setText(dekripsi(fieldChipperTeksDek.getText(), fieldKunciDek1.getText(), fieldKunciDek2.getText()));

    }//GEN-LAST:event_buttonProsesDekActionPerformed

    private void fieldKunciEn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciEn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKunciEn1ActionPerformed

    private void buttonProsesEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesEnActionPerformed
        if (!fieldPlainTeksEn.getText().isEmpty() && !fieldKunciEn1.getText().isEmpty()) {
            fieldChipperTeksEn.setText(enkripsi(fieldPlainTeksEn.getText(), fieldKunciEn1.getText(), fieldKunciEn2.getText()));

            fieldChipperTeksDek.setText(fieldChipperTeksEn.getText());
            fieldKunciDek1.setText(fieldKunciEn1.getText());
        }
        fieldKunciDek2.setText(fieldKunciEn2.getText());
    }//GEN-LAST:event_buttonProsesEnActionPerformed

    private void fieldChipperTeksEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldChipperTeksEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldChipperTeksEnActionPerformed

    private void fieldPlainTeksDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlainTeksDekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlainTeksDekActionPerformed

    private void fieldKunciDek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciDek2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKunciDek2ActionPerformed

    private void fieldKunciEn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciEn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKunciEn2ActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        new FormEncryptionApp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReset1ActionPerformed
        kliken = 0;
        klikdek = 0;
        fieldKunciEn1.setText("");
        fieldKunciEn2.setText("");
    }//GEN-LAST:event_buttonReset1ActionPerformed

    private void buttonReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReset2ActionPerformed
        kliken = 0;
        klikdek = 0;
        fieldKunciDek1.setText("");
        fieldKunciDek2.setText("");
    }//GEN-LAST:event_buttonReset2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalTwoKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalTwoKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalTwoKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalTwoKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPolyalphabeticalTwoKey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonProsesDek;
    private javax.swing.JButton buttonProsesEn;
    private javax.swing.JButton buttonReset1;
    private javax.swing.JButton buttonReset2;
    private javax.swing.JTextField fieldChipperTeksDek;
    private javax.swing.JTextField fieldChipperTeksEn;
    private javax.swing.JTextField fieldKunciDek1;
    private javax.swing.JTextField fieldKunciDek2;
    private javax.swing.JTextField fieldKunciEn1;
    private javax.swing.JTextField fieldKunciEn2;
    private javax.swing.JTextField fieldPlainTeksDek;
    private javax.swing.JTextField fieldPlainTeksEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
