/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ksi;

/**
 *
 * @author Biekaeksa
 */
public class FormPolyalphabeticalOneKey extends javax.swing.JFrame {

    private char teksGenerate[][] = new char[26][26];

    /**
     * Creates new form FormPolyalphabeticalOneKey
     */
    public FormPolyalphabeticalOneKey() {
        initComponents();
    }

    private String enkripsi(String plainTeks, String key) {
        String chipperText = "";
        plainTeks = plainTeks.toUpperCase();
        key = key.toUpperCase();
        for (int i = 0, j = 0; i < plainTeks.length(); i++) {
            char c = plainTeks.charAt(i);
            if ((c < 'A' || c > 'Z') && c != ' ') {
                continue;
            }
            if(c == ' '){
                chipperText += ' ';
            }else{
                chipperText += (char) ((c + key.charAt(j) - 2 * 'A') % 26 + 'A');
            }
            
            j = ++j % key.length();
        }
        return chipperText;
    }

    private String dekripsi(String chipperText, String key) {
        String plainText = "";
        chipperText = chipperText.toUpperCase();
        key = key.toUpperCase();
        for (int i = 0, j = 0; i < chipperText.length(); i++) {
            char c = chipperText.charAt(i);
            if ((c < 'A' || c > 'Z') && c != ' ') {
                continue;
            }
            if(c == ' '){
                plainText += ' ';
            }else{
                plainText += (char) ((c - key.charAt(j) + 26) % 26 + 'A');
            }
            j = ++j % key.length();
        }
        return plainText;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldPlainTeksEn = new javax.swing.JTextField();
        fieldKunciEn = new javax.swing.JTextField();
        buttonProsesEn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fieldChipperTeksEn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldPlainTeksDek = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldChipperTeksDek = new javax.swing.JTextField();
        fieldKunciDek = new javax.swing.JTextField();
        buttonProsesDek = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("ENKRIPSI TEKNIK POLYALPHABETICAL");

        jLabel2.setText("Plain Teks");

        jLabel3.setText("Kunci 1");

        fieldPlainTeksEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlainTeksEnActionPerformed(evt);
            }
        });

        fieldKunciEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciEnActionPerformed(evt);
            }
        });

        buttonProsesEn.setText("Proses");
        buttonProsesEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesEnActionPerformed(evt);
            }
        });

        jLabel4.setText("Chipper Teks");

        fieldChipperTeksEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldChipperTeksEnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("DEKRIPSI TEKNIK POLYALPHABETICAL");

        fieldPlainTeksDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPlainTeksDekActionPerformed(evt);
            }
        });

        jLabel6.setText("Chippe Teks");

        jLabel7.setText("Kunci 1");

        fieldChipperTeksDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldChipperTeksDekActionPerformed(evt);
            }
        });

        fieldKunciDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKunciDekActionPerformed(evt);
            }
        });

        buttonProsesDek.setText("Proses");
        buttonProsesDek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesDekActionPerformed(evt);
            }
        });

        jLabel8.setText("Plain Teks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldKunciDek, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldChipperTeksDek)
                                    .addComponent(buttonProsesDek)
                                    .addComponent(fieldPlainTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldKunciEn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPlainTeksEn)
                                    .addComponent(buttonProsesEn)
                                    .addComponent(fieldChipperTeksEn, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPlainTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(fieldKunciEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonProsesEn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(fieldChipperTeksEn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fieldChipperTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(fieldKunciDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonProsesDek)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(fieldPlainTeksDek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldPlainTeksEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlainTeksEnActionPerformed

    }//GEN-LAST:event_fieldPlainTeksEnActionPerformed

    private void fieldKunciEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKunciEnActionPerformed

    private void buttonProsesEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesEnActionPerformed
        if (!fieldPlainTeksEn.getText().isEmpty() && !fieldKunciEn.getText().isEmpty()) {
            fieldChipperTeksEn.setText(enkripsi(fieldPlainTeksEn.getText(), fieldKunciEn.getText()));

            fieldChipperTeksDek.setText(fieldChipperTeksEn.getText());
            fieldKunciDek.setText(fieldKunciEn.getText());
        }
    }//GEN-LAST:event_buttonProsesEnActionPerformed

    private void fieldChipperTeksEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldChipperTeksEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldChipperTeksEnActionPerformed

    private void fieldPlainTeksDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPlainTeksDekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPlainTeksDekActionPerformed

    private void fieldChipperTeksDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldChipperTeksDekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldChipperTeksDekActionPerformed

    private void fieldKunciDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKunciDekActionPerformed

    }//GEN-LAST:event_fieldKunciDekActionPerformed

    private void buttonProsesDekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesDekActionPerformed
        fieldPlainTeksDek.setText(dekripsi(fieldChipperTeksDek.getText(), fieldKunciDek.getText()));
    }//GEN-LAST:event_buttonProsesDekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalOneKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalOneKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalOneKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPolyalphabeticalOneKey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPolyalphabeticalOneKey().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProsesDek;
    private javax.swing.JButton buttonProsesEn;
    private javax.swing.JTextField fieldChipperTeksDek;
    private javax.swing.JTextField fieldChipperTeksEn;
    private javax.swing.JTextField fieldKunciDek;
    private javax.swing.JTextField fieldKunciEn;
    private javax.swing.JTextField fieldPlainTeksDek;
    private javax.swing.JTextField fieldPlainTeksEn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
